API.html, TileStache/Vector/__init__.py
Sparsely populated columns (like OSM buildings' height attribute) create a lot of null values in the feature's properties dictionary. This change allows to opt out of this behavior.
=> VectorLayer: Skip null properties.

TileStache/Vector/__init__.py
If the driver name is `ESRI Shapefile`, `GeoJSON` or `SQLite` and the `file`
parameter is missing it returned the error:
```
Need at least a "file" parameter for a shapefile
```
Changed it to
```
Need a "file" parameter
```
to reflect that it applies to all three driver types and avoid confusing the user.
=> Clarify exception

TileStache/Core.py
Deleting items from the list without an index will
have to search the whole list, so the loop will have
O(n^2) performance. Instead, we just remember the index
of the first tile that is still new enough and then
cut off the list at that point. Performance should now be O(n).
Note that it might be even better (more transparent)
to use an OrderedDict here.
fixes #229
=> Improved performance of _addRecentTile

TileStache/S3.py
If locks are disabled, this is unnecessary work.
=> Don't attempt to unlock if locks aren't in use

TileStache/Core.py
`NoTileLeftBehind` is intended to bypass caches. It does for local caches, but it inherits the default rendering behavior, which is to return a 200 HTTP response. This means that empty tiles (not intended to be cached) are treated as cacheable by downstream requestors.
=> NoTileLeftBehind should return 404s

Vagrantfile
Replaced Vagrant box since existing URL was broken. Now using Hashicorp-provided Ubuntu base box.
Here's the box it pulls now:
https://atlas.hashicorp.com/ubuntu/boxes/trusty64
=> Vagrant box URL was 404. Replace with working box.

TileStache/__init__.py
The Expires header is missing a comma after the day, which makes it non-compliant with RFC 1123, and thus prevents caching by some proxies and CDNs.
=> Make "Expires" header RFC 1123 compliant

TileStache/Providers.py
According to the urllib2 documentation this allow to use the environment variable <protocol>_proxy
See: https://docs.python.org/2/library/urllib2.html#urllib2.ProxyHandler
=> Let urllib2 get proxies if set in the environment variables

man/tilestache-compose.1, man/tilestache-list.1
The lintian QA tool reported the missing manpages for the Debian package build.
=> Add missing manpages.

tests/cache_tests.py, tests/provider_tests.py, tests/vectiles_tests.py, tests/vector_tests.py
Set OFFLINE_TESTS in the environment to skip tests requiring network.
Set NO_DATABASE in the environment to skip tests requiring a database.
The Debian package build environment doesn't provide network connectivity which is prohibited by the Debian Policy, nor is a database setup in the build environment.
=> Skip tests requiring network and other unmet prerequisites.

TileStache/Core.py
Commit https://github.com/TileStache/TileStache/commit/92885db6286343fb194a28f080db8572c4b662d8#diff-69eff754f6846d301d1865dc9b2d7458 removed the ability to use the Preview function when using TileStache as a raster tile viewer.
The upgrade is calling a new `MM.TemplatedLayer` but the JS referenced in https://github.com/TileStache/TileStache/blob/master/TileStache/Core.py#L736 points to URL http://code.modestmaps.com/tilestache/modestmaps.min.js that does not contain the `TemplatedLayer` string at all. I've changed the reference to the current tagged script of ModestMap that does contain `TemplatedLayer` string.
The removal in the same commit of `new MM.Hash(map);` removed the ability when you pan in the viewer to keep center and zoom in the URL as you move.
When you use default …
=> Fix regressions due to unchanged reference to external JS file and hash removal

.travis.yml, README.md, TileStache/Caches.py, TileStache/Config.py, TileStache/Core.py, TileStache/Geography.py, TileStache/Goodies/VecTiles/client.py, TileStache/Goodies/VecTiles/geojson.py, TileStache/Goodies/VecTiles/mvt.py, TileStache/Goodies/VecTiles/server.py, TileStache/Goodies/VecTiles/topojson.py, TileStache/Goodies/VecTiles/wkb.py, TileStache/Memcache.py, TileStache/Pixels.py, TileStache/Providers.py, TileStache/Vector/Arc.py, TileStache/Vector/__init__.py, TileStache/__init__.py, requirements.txt, setup.py, tests/cache_tests.py, tests/provider_tests.py, tests/servers/dummy-response-server.py, tests/utils.py, tests/vectiles_tests.py, tests/vector_tests.py
Add support for use with Python 3, including explicit string/bytes usage, 2/3 compatible package imports, fixed circular and implicit imports, upstream Modest Maps compatibility, and various small syntax and value updates.
Update: everything now passes 🎉.
=> Support Python 3

TileStache/Core.py
If the preview is served from behind an https proxy, then browsers will complain about the content being mixed-mode and not load the `modestmaps-js` script. By removing protocol from the `<script>` tag, the protocol of the current page will be used by the browser.
=> Fix preview protocol when running under https

TileStache/Goodies/VecTiles/server.py
When you have a layer defined like this:
"myLayer": {
...
"provider": {
"class": "TileStache.Goodies.VecTiles:Provider",
"kwargs": {
...
"queries": ["SELECT  ST_Transform(sth.geom, 900913)  AS **geometry**,sth.id as id from sth WHERE sth.status=0"]
}
},
...
}
If there is no object like this in database, an error 500 is triggered:
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 180, in run_wsgi
execute(self.server.app)
File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 168, in execute
application_iter = app(environ, start_response)
File "/usr/local/lib/python2.7/dist-packages/TileStache-1.50.1-py2.7.egg/TileStache/**init**.py", line 381, in **call**
status_code, headers, content = requestHandler2(self.config, …
=> Fix error 500 when db query returns no object in the layer

TileStache/MBTiles.py
MBTiles databases can contain PBF vector tiles.
=> Allow PBF format for MBTiles output

TileStache/__init__.py
this should add compatibility for python3. my goal is to port [fff-monitoring](https://github.com/asdil12/fff-monitoring) to a single python3 app. currently it is split into a python3 part for the flask app and a python2 app for tilestach/mapnik.
the patch was tested with the following code (and seems to provide the same output on python 2.7 and python 3.5):
```python
from TileStache import WSGITileServer
from TileStache.Config import buildConfiguration
def get_app():
return WSGITileServer(config=buildConfiguration({
"cache": {
"name": "Disk",
"path": "tilestach_cache"
},
"layers": {
"testing": {
"provider": {
"class": "TileStache.Mapnik.ImageProvider",
"kwargs": {
"mapfile": "testing.xml"
}
},
"metatile": {"buffer": 128},
"cache lifespan": 300
},
},
"logging": "debug",
})
)
def main(): …
```
=> python3 compatibility for WSGITileServer

README.md
User is informed when using the old script to use a new link available from https://bootstrap.pypa.io/get-pip.py
=> Update get-pip.py location

README.md
See Issue: #317
Mapbox dropped the "mapbox_vector_tile" package from their dependency list.
Therefore users that want to use TileStache.Goodies.VecTiles as a provider need to install via pip install mapbox-vector-tile
=> "mapbox_vector_tile" missing as a dependency

TileStache/Mapnik.py
First of all, thanks for your work on this great project. We use this for one of our products and encountered an issue while porting our code to python 3. Would be great to have this fix merged into master so that we don't need our fork anymore.
=> Fix for making GridProvider python 3 ready

TileStache/Mapnik.py
Newer versions of the Mapnik API change the FontEngine API a little bit. This commit tweaks so that both the old and new APIs can be used.
=> Modify so that Mapnik FontEngine API can be used with old and new Mapnik builds

TileStache/Mapnik.py, TileStache/py3_compat.py
This fixes a bug having to do with "unichar" that does not exist in Python 3
=> Python 3 compat: unichar

TileStache/Memcache.py
Memcache keys can only have 250 chars, so for extremely long layer names use a SHA-1 hash infix.
Examples:
```Python
>>> Memcache.tile_key(Layer('doof'), coord, 'GeoJSON', 1, 'prefix')
'prefix/1/doof/12/656/1582.GeoJSON'
>>> Memcache.tile_key(Layer('doof.'* 10), coord, 'GeoJSON', 1, 'prefix')
'prefix/1/doof.doof.doof.doof.doof.doof.doof.doof.doof.doof./12/656/1582.GeoJSON'
>>> Memcache.tile_key(Layer('doof.'* 100), coord, 'GeoJSON', 1, 'prefix')
'prefix/1/doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.de0f4f765ddb634728fa40a9ce028e863ff80e17bdoof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof.doof./12/656/1582.GeoJSON'
```
=> Limit memcache key length for very long layer names

setup.py
Newer version of flask require newer versions of Werkzeug.
The warning message is as follows:
```
flask 1.0.2 has requirement Werkzeug>=0.14, but you'll have werkzeug 0.11.3 which is incompatible.
tilestache 1.51.12 has requirement Werkzeug==0.11.13, but you'll have werkzeug 0.11.3 which is incompatible.
```
=> Allow Werkzeug versions other than 0.11.13

TileStache/Goodies/Providers/Composite.py, TileStache/Goodies/Providers/MirrorOSM.py, TileStache/Goodies/VecTiles/client.py, TileStache/Goodies/VecTiles/mvt.py, TileStache/Goodies/VecTiles/server.py, TileStache/Goodies/VecTiles/wkb.py
Use io.BytesIO instead of StringIO when convenient. See #302, #291.
Fix EmptyResponse for PBF format.
=> Fix MVT related issues
